<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_invalid Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c93575bc-dc05-4493-b248-c08e5df80a33</testSuiteGuid>
   <testCaseLink>
      <guid>784a40c5-973c-42e7-96db-9fdf3013c584</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>4d028dc6-b7b9-4df7-991f-5cef4d8fa155</id>
         <masked>false</masked>
         <name>username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/TC002_invalid Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>60f9117a-f147-4c39-b79b-6906b5df99bc</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>4-6</value>
         </iterationEntity>
         <testDataId>Data Files/loginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>60f9117a-f147-4c39-b79b-6906b5df99bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>4d028dc6-b7b9-4df7-991f-5cef4d8fa155</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>60f9117a-f147-4c39-b79b-6906b5df99bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>bdbe8406-a2da-4e01-996a-305eb0bee2b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>60f9117a-f147-4c39-b79b-6906b5df99bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Message</value>
         <variableId>f2743c97-1e7e-4480-ac5b-e9fe8b160a5c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
